<a href="https://colab.research.google.com/github/kerenalli/MyExamplePython/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vectors in Python

In [1]:
from numpy import array
a=array([1,2,3,4])
print (a)

[1 2 3 4]


In [2]:
#another vector
b=array([4,3,2,1])
print(b)

[4 3 2 1]


In [3]:
#multiply vectors
c=a*b
print(c)

[4 6 6 4]


Matrix

In [5]:
A=array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [6]:
B=array([[6,5,4],[3,2,1]])
print(B)

[[6 5 4]
 [3 2 1]]


In [7]:
C=A+B
print(C)


[[7 7 7]
 [7 7 7]]


In [8]:
D=B-A
print(D)

[[ 5  3  1]
 [-1 -3 -5]]


In [10]:
E=A-B
print(E)

[[-5 -3 -1]
 [ 1  3  5]]


In [30]:
#Matrix dot product
from numpy import array
A=array([[1,2],[3,4]])
print(A)
B=array([[1,2],[2,3],[3,4]])
print(B)
C = B.dot(A)
print(C)

[[1 2]
 [3 4]]
[[1 2]
 [2 3]
 [3 4]]
[[ 7 10]
 [11 16]
 [15 22]]


In [26]:
# matrix dot product
from numpy import array
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
B = array([[1, 2], [3, 4]])
print(B)
C = A.dot(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]


Matrix Transpose

In [33]:
A=array([[1,2],[3,4]])
F=A.T
print(A)
print("\n")
print(F)

[[1 2]
 [3 4]]


[[1 3]
 [2 4]]


In [35]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([[1, 2], [3, 4]])
print(A)
# invert matrix
B = inv(A)
print(B)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [40]:
#Lower and Upper Triangular Matrix
# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# LU decomposition
P, L, U = lu(A)
print("\nOriginal P: \n")
print(P)
print("\nLower Composition L: \n")
print(L)
print("\nUpper Composition U: \n")
print(U)
# reconstruct
print("\nReconstructed P: \n")
B = P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Original P: 

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

Lower Composition L: 

[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

Upper Composition U: 

[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]

Reconstructed P: 

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Singular Value Decomposition

In [44]:
from numpy import array
from scipy.linalg import svd
A=array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
U,s,V=svd(A)
print("\nU\n")
print(U)
print("\ns\n")
print(s)
print("\nV\n")
print(V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

U

[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

s

[1.68481034e+01 1.06836951e+00 4.41842475e-16]

V

[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
