<a href="https://colab.research.google.com/github/kerenalli/MyExamplePython/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
#Tensor: A n-D array/vector
# t1 here is a Scalar
t1=torch.tensor(4.0)
print(t1)
print("data type of t1: ",t1.dtype)

tensor(4.)
data type of t1:  torch.float32


In [7]:
#Tensor: A 1-D vector
#t2 here is a vector
t2=torch.tensor([1,2,3,4.])
print(t2)

tensor([1., 2., 3., 4.])
data type of t2:  torch.float32


In [14]:
#t3: a 2 D matrix
t3=torch.tensor([[1,2],[3,4]])
print(t3)
t3.shape

tensor([[1, 2],
        [3, 4]])


torch.Size([2, 2])

In [16]:
#t4: a 3d array
t4=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],
                 [[10,11,12],[13,14,15],[16,16,17]]
                  ])
print(t4)
t4.shape

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 16, 17]]])


torch.Size([2, 3, 3])

Tensor operations and gradients

In [21]:
#create tensors
x=torch.tensor(3.)
w=torch.tensor(4., requires_grad=True)
z=torch.tensor(5., requires_grad=True)
x,w,z


(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [24]:
#arithmetic operations
y=w*x+z
y

tensor(17., grad_fn=<AddBackward0>)

In [27]:
#compute derivates 
y.backward
y

tensor(17., grad_fn=<AddBackward0>)

In [26]:
#display the gradients
print('dy/dx: ', x.grad)
print('dy/dw: ', w.grad)
print('dy/dz: ', z.grad)

dy/dx:  None
dy/dw:  None
dy/dz:  None


In [31]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3,3), 42)
t6

tensor([[42, 42, 42],
        [42, 42, 42],
        [42, 42, 42]])

In [34]:
#concatinate tensors
t7=torch.cat((t6,t6))
t7


tensor([[42, 42, 42],
        [42, 42, 42],
        [42, 42, 42],
        [42, 42, 42],
        [42, 42, 42],
        [42, 42, 42]])

In [49]:
#compute the sin of each tensor
t8 = torch.sin(t2)
t8
t9 = t8.reshape(2, 2, 1)
t9


tensor([[[ 0.8415],
         [ 0.9093]],

        [[ 0.1411],
         [-0.7568]]])

In [50]:
#create an array in Numpy:
import numpy as np
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [53]:
# Convert the numpy array to a torch tensor.
p=torch.from_numpy(x)
p

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [55]:
# Convert a torch tensor to the numpy array
x=p.numpy()
x

array([[1., 2.],
       [3., 4.]])

Save and upload your notebook

In [56]:
#instal jovian
!pip install jovian --upgrade --quiet


     |████████████████████████████████| 71kB 4.3MB/s 
